app/models/userModel.py
from flask_login import UserMixin
# from app.utils.db import get_db

class UserModel(UserMixin):
    def __init__(self, id_, name, email, profile_pic):
        self.id_ =id_
        self.name =name
        self.email =email
        self.profile_pic =profile_pic
    
    # def get(self, user_id):
    #     db =get_db() 
    #     user =db.execute("SELECT * FROM users WHERE id =?", (user_id,))  .fetchone()
    #     if not user: return 
    #     return UserModel(*user)
    
    # @staticmethod
    # def create(id_, name, email, profile_pic):
    #     db =get_db()
    #     db.execute("INSERT INTO users (id, name, email, profile_pic)" "VALUES (?, ?, ?, ?)", (id_, name, email, profile_pic))
    #     db.commit()

app/__init__.py
from flask import Flask
from app.utils.constants import BASEDIR
from app.routes import auth, public 
# from app.utils.login_manager import manage_login

def createapp(test_config:dict =None)->Flask:
    """
    Creates and returns a new Flask app instance

    :param test_config? {dict} - app test configurations
    :return app {Flask} - Flask instance created 
    """

    app =Flask(__name__, template_folder =BASEDIR /'templates', static_folder =BASEDIR /'static')

    if test_config: app.config.from_object(test_config)
    else: app.config.from_pyfile(BASEDIR /'config.py') 
    # manage_login(app =app)

    app.register_blueprint(public, url_prefix ='/')
    app.register_blueprint(auth, url_prefix ='/auth')

    return app

app/routes/__init__.py
from .auth_route import auth
from .public_route import public

app/routes/auth_route.py
from app.views.auth_view import login, logout, callback
from flask import Blueprint

auth =Blueprint('auth', __name__)

auth.route('', methods =['GET','POST'])(login)
auth.route('<string:provider>-auth', methods =['GET','POST'])(login)
auth.route('/callback/<string:provider>', methods =['GET'])(callback)
auth.route('/logout', methods =['GET'])(logout)

app/routes/public_route.py
from flask import Blueprint
from app.views.public_view import home

public =Blueprint('public', __name__)
public.route('', methods =['GET'])(home)

app/views/auth_view.py
from flask import request, jsonify, redirect, url_for, session
from app.services.auth_service import manual_auth_service
from app.utils.constants import PROVIDER_AUTH_SERVICES, PROVIDER_AUTH_CALLBACK_SERVICES

def login(provider =None): 
    """
        Authenticate and manage user sessions

        :param provider {str} - provider to navigate to. 
    """ 
    service =PROVIDER_AUTH_SERVICES.get(provider)()
    if request.method =='POST':
        form =request.form
        service =manual_auth_service({**form})  
    if not service: return {'error': 'Page Not Found'}

    return service

def callback(provider:str): 

    """
        Provider callback view. Bridge between the provider auth service and the client app

        :param provider {str} - the provider from which we are fetching the data
        :returns data {dict} - the client information received from the callback url
    """
    service =PROVIDER_AUTH_CALLBACK_SERVICES.get(provider)() 
    return service

def logout(): 
    """
        Ends user session and redirects user to the login screen
    """
    session.clear()
    session =None
    return redirect(url_for('public.home'))

app/views/public_view.py
from flask import render_template

def home()->str:
    """
        Home view: returns an html template string
        :return template {str} html5 string to be rendered to the client
    """
    return render_template('index.html')

main.py
from app import createapp

app =createapp()

if __name__ == '__main__': app.run()

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python-Flask Social Login</title>
    <link rel="stylesheet" href="{{url_for('static', filename ='css/styles.css')}}">
</head>
<body>
    <form method="post" action="{{url_for('auth.login')}}">
        <h2>Login Here</h2>
        <div> 
            <input type="email" name ="email" id ="email" placeholder="enter email"/>
            <input type="password" name ="password" id ="password" placeholder="enter password"/>
            <input type="submit" value="Login" />
        </div> 
        Or Sign In Using 
        <div>
            <a href="{{ url_for('auth.login', provider ='facebook' ) }}">Facebook</a>
            <a href="{{ url_for('auth.login', provider ='twitter' ) }}">Twitter</a> 
            <a href="{{ url_for('auth.login', provider ='google' ) }}">Google</a>
            <a href="{{ url_for('auth.login', provider ='github' ) }}">Github</a> 
        </div>
    </form> 
</body>
</html>